version: '3.7'
services:
  server:
    container_name: server
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/server
    command: npm run server

  client:
    depends_on: 
      - server
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - 3000:3000
    volumes:
    - ./client:/client
    links:
      - server
    command: npm run start