version: '3.7'
services:
  server:
    container_name: server
    restart: always
    build:
      context: ./server
    ports:
      - 5000:5000
    environment:
      NODE_ENV: production
    command: node server.js

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 80:80
    links:
      - server
    restart: always


